#!/usr/bin/bash

[[ -z "$db97" ]] && { echo "Script isn't intended to run standalone, instead as part of 'db97' script"; exit 1; }
source sys_utilities.sh 2> /dev/null || { echo "Couldn't import 'sys_utilities'"; exit 1; }

shopt -s extglob
export LC_COLLATE=C

get_db_name() {
  echo
  read -rp "DB name ('q' to quit): " db_name
  is_quit "$db_name" && exit 0;
}

get_db_name
while [[ ! -d "$db97/${db_name:-0}/" ]]; do
  echo "There is no database with the name $db_name"
  get_db_name
done

#           0             1             2                 3                 4                 5                   6          7
opts=("Create Table" "List Tables" "Drop Table" "Insert Into Table" "Select from Table" "Delete from Table" "Update Table" "Exit")
echo "Connect to $db_name"

while true; do
  echo
  for i in ${!opts[@]}; do
    echo "[$((i+1))] ${opts[i]}"
  done
  
  read -rp "$db_name _> " opt
  if [[ "$opt" =~ ^[1-8]$ ]]; then
    opt="${opts[opt-1]}"
  else
    opt="wrong"
  fi
  case $opt in
    ${opts[0]})                     # Create Table
      echo
      create_table "$db_name"
    ;;
    
    ${opts[1]})                     # List Tables
      echo
      list_table "$db_name"
    ;;
    
    ${opts[2]})                     # Drop Table
      echo
      drop_table "$db_name"
    ;;
    
    ${opts[3]})                     # Insert Into Table
      insert_in_table "$db_name"
    ;;
    
    ${opts[4]})                     # Select from Table
      select_from_table "$db_name"
    ;;
    
    ${opts[5]})
      echo "To Do"
    ;;
    
    ${opts[6]})
      echo
      update_table "$db_name"
    ;;
    
    ${opts[7]})
      echo "Disconnect from $db_name"
      exit 0
    ;;
    
    *)
      echo "Wrong Choice"
    ;;
  esac
  echo -e "\n++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
done
