#!/usr/bin/bash

[[ -z "$db97" ]] && { echo "Script isn't intended to run standalone, instead as part of 'db97' script"; exit 1; }
source sys_utilities.sh 2> /dev/null || { echo "Couldn't import 'sys_utilities'"; exit 1; }

shopt -s extglob
export LC_COLLATE=C

get_db_name() {
  read -rp "DB name ('q' to quit): " db_name
  is_quit "$db_name" && exit 0;
}

get_db_name
while [[ ! -d "$db97/${db_name:-0}/" ]]; do
  echo "There is no database with the name $db_name"
  get_db_name
done

#           0             1             2                 3                 4                 5                   6
opts=("Create Table" "List Tables" "Drop Table" "Insert Into Table" "Select from Table" "Delete from Table" "Update Table")
echo -e "Connect to $db_name\n"

menu "$db_name" "${opts[@]}"; status="$?";
while [[ "$status" -ne 0 ]]; do
  choice="${opts[status-1]}"
  echo
  case "$choice" in
    "${opts[0]}")                     # Create Table
      create_table "$db_name"
    ;;

    "${opts[1]}")                     # List Tables
      list_table "$db_name"
    ;;

    "${opts[2]}")                     # Drop Table
      drop_table "$db_name"
    ;;

    "${opts[3]}")                     # Insert Into Table
      insert_in_table "$db_name"
    ;;

    "${opts[4]}")                     # Select from Table
      select_from_table "$db_name"
    ;;

    "${opts[5]}")                     # Delete from Table
      echo "To Do"
    ;;

    "${opts[6]}")                       # Update in Table
      update_table "$db_name"
    ;;

    *)
      echo "Wrong Choice"
    ;;
  esac

  echo
  for _ in {1..80}; do
    echo -n "-"
  done
  echo -e "\n"

  menu "$db_name" "${opts[@]}"; status="$?";
done

exit 0
