#!/usr/bin/bash

echo '                                                   ';
echo ' ██████████   ███████████      ████████  ██████████';
echo '░░███░░░░███ ░░███░░░░░███    ███░░░░███░███░░░░███';
echo ' ░███   ░░███ ░███    ░███   ░███   ░███░░░    ███';
echo ' ░███    ░███ ░██████████    ░░█████████      ███';
echo ' ░███    ░███ ░███░░░░░███    ░░░░░░░███     ███';
echo ' ░███    ███  ░███    ░███    ███   ░███    ███';
echo ' ██████████   ███████████    ░░████████    ███';
echo ' ░░░░░░░░░░   ░░░░░░░░░░░      ░░░░░░░░    ░░░';
echo '                                              ';
echo '                                              ';

# To be able to call the script from any where in the system

script_absolute_path="$(dirname "$(readlink -f "$0")")"
for dir in "$script_absolute_path"/*/; do
  PATH="$dir:$PATH"
done
PATH="$script_absolute_path:$PATH"

# Important Initialization
export db97="$HOME/.db97"
source "sys_utilities.sh" || { echo "Couldn't import 'sys_utilities'"; exit 1; }
opts=("Create DB" "List DB" "Connect DB" "Drop DB")
shopt -s extglob
export LC_COLLATE=C

#Validate DB97 exists or not
if [[ ! -d $db97 ]]
then
  mkdir "$db97" || { echo "Couldn't Create $db97"; exit 1; }
  echo -e "$db97 was created\n";
fi

#Actual Driving Code
menu "DB97" "${opts[@]}"; status="$?"
while [[ "$status" -ne 0 ]]; do
  choice="${opts[status-1]}"
  echo
  case $choice in
    "${opts[0]}")             # Create DB
      create_db
    ;;

    "${opts[1]}")             # List DB
      list_db
    ;;

    "${opts[2]}")             # Connect DB
      connect_db
    ;;

    "${opts[3]}")             # Drop DB
      drop_db
    ;;

    *)
      echo "Wrong Choice"
    ;;
  esac

  echo
  for _ in {1..80}; do
    echo -n ">"
  done
  echo -e "\n"

  menu "DB97" "${opts[@]}"; status="$?"
done

echo "GoodBye"
exit 0
