#!/usr/bin/bash

echo '                                                   ';
echo ' ██████████   ███████████      ████████  ██████████';
echo '░░███░░░░███ ░░███░░░░░███    ███░░░░███░███░░░░███';
echo ' ░███   ░░███ ░███    ░███   ░███   ░███░░░    ███';
echo ' ░███    ░███ ░██████████    ░░█████████      ███';
echo ' ░███    ░███ ░███░░░░░███    ░░░░░░░███     ███';
echo ' ░███    ███  ░███    ░███    ███   ░███    ███';
echo ' ██████████   ███████████    ░░████████    ███';
echo ' ░░░░░░░░░░   ░░░░░░░░░░░      ░░░░░░░░    ░░░';
echo '                                              ';
echo '                                              ';

export db97="$HOME/.db97"
for dir in */; do
  PATH="$PWD/$dir:$PATH"
done
PATH="$PWD:$PATH"

opts=("Create DB" "List DB" "Connect DB" "Drop DB" "Exit")
shopt -s extglob
export LC_COLLATE=C

#Validate DB97 exists or not
if [[ ! -d $db97 ]]
then
  mkdir $db97 || { echo "Couldn't Create $db97"; exit 1; }
  echo -e "$db97 was created\n";
fi

#Actual Driving Code

PS3="DB97 #? "
select choice in "${opts[@]}"
do
  case $choice in
    "${opts[0]}")
      create_db
    ;;
    
    "${opts[1]}")
      list_db
    ;;
    
    "${opts[2]}")
      connect_db
    ;;
    
    "${opts[3]}")
      drop_db
    ;;
    
    "${opts[4]}")
      echo "GoodBye"
      break
    ;;
    
    *)
      echo "Wrong Choice"
    ;;
  esac
done

exit 0
