#!/bin/bash
source table_utilities.sh || { echo "couldn't emport table utilities"; exist 1; }
db_name="$1"

# Name Of The Table That Will Be Update
read -p "Enter The Table To Update: " table_name


if [ -f "$db97/$db_name/$table_name.meta" ]; then
  
  while read -r col; do
    col_types+=("$col");
  done < <(cut -d: -f2 ../.db97/ITI/student.meta )
  
  
  cut -d: -f1 "$db97/$db_name/$table_name.meta" | nl
  echo
  # The Number Of Field To Update
  while true; do
    read -p "Choose The Number Of Field To Update: " field_number
    echo
    # if the input value is a number
    if [[ $field_number =~ ^[0-9]+$ ]]; then
      
      if [[ "$field_number" -le 0 || "$field_number" -gt $(wc -l "$db97/$db_name/$table_name.meta" | cut -d ' ' -f 1) ]]; then
        echo "Sorry - The Value Is Out Of Range..."
        continue
      else
        read -p "Enter The Value To Update: " field_value # Enter The Value You Want To Update
        check_type "$field_value" "${col_types[field_number -1]}" && break;
      fi
      
    else
      echo "Wrong Choice, Enter A Valid Number...."
      continue
    fi
  done
  
else
  echo "Sorry - "$table_name" Table Is Not Exist..."
  exit 1
fi




while true; do
  cut -d: -f1 "$db97/$db_name/$table_name.meta" | nl
  echo
  read -rp "Search For The Record By: " table_record # Search The Record By
  echo
  
  if [[ $table_record =~ ^[0-9]+$  ]]; then  # It's commonly used in conditional statements to test if a variable contains any value or is empty.
    
    if [[ "$table_record" -le 0 || "$table_record" -gt $(wc -l "$db97/$db_name/$table_name.meta" | cut -d ' ' -f 1) ]]; then
      echo "The Choice Is Out Of The Range, Enter A Valid Number..."
      continue
    else
      read -rp "Enter The Value Search By: " record_value
      check_type "$record_value" "${col_types[table_record -1]}" &&  break;
    fi
  else
    echo "Wrong Choice, Enter A Valid Number..."
    break
  fi
done

awk -F: -v fn="$field_number" -v fv="$field_value" -v tr="$table_record" -v rv="$record_value" '{ if ($tr == rv) { $fn = fv; print} else { print } }' "$db97/$db_name/$table_name"



# Error Handling :
# - No input detected
# - Out Of The Range
# - is a number Datatype
# - is file is exist or not


#cut -d: -f1 "$db97/$db_name/$table_name.meta"

# 1 ID:int:pk
# 2 Name:string:nn,u
# 3 Track:string:nn
